protected/modules/menu/models/MenuItem.php
<?php
/**
 * Menu основная модель для пунктов меню
 *
 * @author yupe team <team@yupe.ru>
 * @link http://yupe.ru
 * @copyright 2009-2013 amyLabs && Yupe! team
 * @package yupe.modules.menu.models
 * @since 0.1
 *
 */

/**
 * This is the model class for table "menu_item".
 *
 * The followings are the available columns in table 'menu_item':
 * @property string $id
 * @property string $parent_id
 * @property string $menu_id
 * @property string $title
 * @property string $href
 * @property string $class
 * @property string $title_attr
 * @property string $before_link
 * @property string $after_link
 * @property string $target
 * @property string $rel
 * @property string $condition_name
 * @property integer $condition_denial
 * @property integer $sort
 * @property integer $status
 * @property boolean $regular_link
 *
 * The followings are the available model relations:
 * @property Menu $menu
 */
class MenuItem extends yupe\models\YModel
{
    const STATUS_DISABLED = 0;
    const STATUS_ACTIVE   = 1;

    /**
     * Returns the static model of the specified AR class.
     * @param string $className active record class name.
     * @return MenuItem the static model class
     */
    public static function model($className = __CLASS__)
    {
        return parent::model($className);
    }

    /**
     * @return string the associated database table name
     */
    public function tableName()
    {
        return '{{menu_menu_item}}';
    }

    /**
     * @return array validation rules for model attributes.
     */
    public function rules()
    {
        // NOTE: you should only define rules for those attributes that
        // will receive user inputs.
        return array(
            array('parent_id, menu_id, title, href', 'required', 'except' => 'search'),
            array('sort, status, condition_denial', 'numerical', 'integerOnly' => true),
            array('parent_id, menu_id, rel, target', 'length', 'max' => 10),
            array('title, href, condition_name, title_attr, before_link, after_link', 'length', 'max' => 255),
            array('class', 'length', 'max' => 50),
            array('regular_link', 'boolean'),
            // The following rule is used by search().
            // Please remove those attributes that should not be searched.
            array('id, parent_id, menu_id, title, href, sort, status, condition_name, condition_denial', 'safe', 'on' => 'search'),
        );
    }

    /**
     * @return array relational rules.
     */
    public function relations()
    {
        // NOTE: you may need to adjust the relation name and the related
        // class name for the relations automatically generated below.
        return array(
            'menu'   => array(self::BELONGS_TO, 'Menu', 'menu_id'),
            'parent' => array(self::BELONGS_TO, 'MenuItem', 'parent_id')
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels()
    {
        return array(
            'id'               => Yii::t('MenuModule.menu', 'Id'),
            'parent_id'        => Yii::t('MenuModule.menu', 'Parent'),
            'menu_id'          => Yii::t('MenuModule.menu', 'Menu'),
            'title'            => Yii::t('MenuModule.menu', 'Title'),
            'href'             => Yii::t('MenuModule.menu', 'Address'),
            'title_attr'       => Yii::t('MenuModule.menu', 'Attribute title'),
            'class'            => Yii::t('MenuModule.menu', 'Attribute class'),
            'rel'              => Yii::t('MenuModule.menu', 'Attribute rel'),
            'target'           => Yii::t('MenuModule.menu', 'Attribute target'),
            'before_link'      => Yii::t('MenuModule.menu', 'Text before link'),
            'after_link'       => Yii::t('MenuModule.menu', 'Text after link'),
            'condition_name'   => Yii::t('MenuModule.menu', 'Condition'),
            'condition_denial' => Yii::t('MenuModule.menu', 'False condition'),
            'sort'             => Yii::t('MenuModule.menu', 'Sorting'),
            'status'           => Yii::t('MenuModule.menu', 'Status'),
            'regular_link'     => Yii::t('MenuModule.menu', 'Regular link'),
        );
    }

    /**
     * @return array customized attribute descriptions (name=>description)
     */
    public function attributeDescriptions()
    {
        return array(
            'id'               => Yii::t('MenuModule.menu', 'Menu item Id'),
            'parent_id'        => Yii::t('MenuModule.menu', 'Item parent. Check root if it is in root menu'),
            'menu_id'          => Yii::t('MenuModule.menu', 'For which one this item is attitude'),
            'title'            => Yii::t('MenuModule.menu', 'Item title'),
            'href'             => Yii::t('MenuModule.menu', 'Page address'),
            'class'            => Yii::t('MenuModule.menu', 'Add necessary classes to &lt;li&gt; tag'),
            'title_attr'       => Yii::t('MenuModule.menu', 'Add notice to link'),
            'rel'              => Yii::t('MenuModule.menu', 'Using for xfr'),
            'target'           => Yii::t('MenuModule.menu', 'Using for open new page in new window or frame'),
            'before_link'      => Yii::t('MenuModule.menu', 'Text before link'),
            'after_link'       => Yii::t('MenuModule.menu', 'Text after link'),
            'condition_name'   => Yii::t('MenuModule.menu', 'Select condition for menu item visibility'),
            'condition_denial' => Yii::t('MenuModule.menu', 'Condition use in conjuction or negation'),
            'sort'             => Yii::t('MenuModule.menu', 'Item order number in menu'),
            'status'           => Yii::t('MenuModule.menu', 'Choose menu item status: <br /><br /><span class="label label-success">activ</span> &ndash; Item and it descendants will be visible.<br /><br /><span class="label label-warning">not active</span> &ndash; Item and it descendants will be hidden.'),
            'regular_link'     => Yii::t('MenuModule.menu', 'Don\'t handle address to router'),
        );
    }

    /**
     * Retrieves a list of models based on the current search/filter conditions.
     * @return CActiveDataProvider the data provider that can return the models based on the search/filter conditions.
     */
    public function search()
    {
        // Warning: Please modify the following code to remove attributes that
        // should not be searched.

        $criteria = new CDbCriteria;

        $criteria->compare('t.id', $this->id, true);
        $criteria->compare('t.parent_id', $this->parent_id, true);
        $criteria->compare('t.menu_id', $this->menu_id, true);
        $criteria->compare('t.title', $this->title, true);
        $criteria->compare('t.href', $this->href, true);

        if ($this->condition_name != '0') {
            $criteria->compare('t.condition_name', $this->condition_name, true);
            
            if ($this->condition_name != '') {
                $criteria->compare('t.condition_denial', $this->condition_denial);
            }
        } else {
            $criteria->condition('t.condition_name', '');
        }

        $criteria->compare('t.sort', $this->sort);
        $criteria->compare('t.status', $this->status);
        $criteria->with = array('menu','parent');

        return new CActiveDataProvider(
            get_class($this), array(
                'criteria' => $criteria,
                'sort'     => array('defaultOrder' => 't.sort')
            )
        );
    }


    public function scopes()
    {
        return array(
            'public' => array(
                'condition' => 'status = :status',
                'params' => array(
                    ':status' => self::STATUS_ACTIVE
                )
            )
        );
    }

    protected function afterSave()
    {
        Yii::app()->cache->clear($this->menu->code);

        return parent::afterSave();
    }

    protected function afterDelete()
    {
        Yii::app()->cache->clear($this->menu->code);

        return parent::afterDelete();
    }

    public function getMenuList()
    {
        return CHtml::listData(Menu::model()->findAll(array('select' => 'id, name')), 'id', 'name');
    }

    public function getStatusList()
    {
        return array(
            self::STATUS_ACTIVE   => Yii::t('MenuModule.menu', 'active'),
            self::STATUS_DISABLED => Yii::t('MenuModule.menu', 'not active'),
        );
    }

    public function getStatus()
    {
        $data = $this->statusList;
        return isset($data[$this->status]) ? $data[$this->status] : Yii::t('MenuModule.menu', '*unknown*');
    }

    public function getParentList()
    {
        return array(0 => Yii::t('MenuModule.menu', 'Menu root')) + CHtml::listData($this->findAll(array('select' => 'id, title')), 'id', 'title');
    }

    public function getParentTree()
    {
        return array(0 => Yii::t('MenuModule.menu', 'Menu root')) + $this->parentTreeIterator;
    }

    public function getParentTreeIterator($parent_id = 0, $level = 1)
    {
        $results = $this->findAll(array(
            'order'     => 'sort',
            'condition' => 'parent_id = :parent_id AND id <> :id AND menu_id = :menu_id',
            'params'    => array(
                'parent_id' => (int) $parent_id,
                'id'        => (int) $this->id,
                'menu_id'   => (int) $this->menu_id,
            ),
        ));

        $items = array();
        if (empty($results))
            return $items;

        foreach ($results as $result)
        {
            $childItems = $this->getParentTreeIterator($result->id, ($level + 1));
            $items += array($result->id => str_repeat('&nbsp;&nbsp;&nbsp;&nbsp;', $level) . $result->title) + $childItems;
        }
        return $items;
    }

    public function getParent()
    {
        return empty($this->parent) ? '---' : $this->parent->title;
    }

protected/modules/menu/controllers/MenuitemBackendController.php
<?php
/**
 * MenuitemBackendController контроллер для управления пунктами меню в панели управления
 *
 * @author yupe team <team@yupe.ru>
 * @link http://yupe.ru
 * @copyright 2009-2013 amyLabs && Yupe! team
 * @package yupe.modules.menu.controllers
 * @since 0.1
 *
 */
class MenuitemBackendController extends yupe\components\controllers\BackController
{
    /**
     * Получаем JSON меню через ajax-запрос:
     * 
     * @return void
     *
     * @throws CHttpException If not ajax/post query || record not found
     */
    public function actionGetjsonitems()
    {
        if (!Yii::app()->getRequest()->getIsPostRequest() || !Yii::app()->getRequest()->getIsAjaxRequest()) {
            throw new CHttpException(404);
        }

        if (($menuId = Yii::app()->getRequest()->getPost('menuId')) !== null){
            throw new CHttpException(404);
        }

        $items = MenuItem::model()->public()->findAll(
            array(
                'condition' => 'menu_id = :menu_id',
                'order'  => 'title DESC',
                'params' => array(
                    ':menu_id' => $menuId
                )
            )
        );

        Yii::app()->ajax->success(
            CHtml::listData(
                $items, 'id', 'title'
            )
        );
    }

    /**
     * Отображает пункт меню по указанному идентификатору
     * 
     * @param integer $id Идинтификатор меню для отображения
     *
     * @return void
     */
    public function actionView($id)
    {
        $this->render('view', array('model' => $this->loadModel($id)));
    }

    /**
     * Создает новую модель пунта меню.
     * Если создание прошло успешно - перенаправляет на просмотр.
     *
     * @return void
     */
    public function actionCreate()
    {
        $model = new MenuItem;

        // Uncomment the following line if AJAX validation is needed
        // $this->performAjaxValidation($model);
        $model->menu_id = Yii::app()->getRequest()->getQuery('mid', null);
        
        if (($data = Yii::app()->getRequest()->getPost('MenuItem')) !== null) {

            $model->setAttributes($data);

            if ($model->save()) {

                Yii::app()->user->setFlash(
                    yupe\widgets\YFlashMessages::SUCCESS_MESSAGE,
                    Yii::t('MenuModule.menu', 'New item was added to menu!')
                );

                $this->redirect(
                    (array) Yii::app()->getRequest()->getPost(
                        'submit-type', array('create')
                    )
                );
            }
        }

        $criteria = new CDbCriteria;

        $criteria->select = new CDbExpression('MAX(sort) as sort');
        
        $max = $model->find($criteria);

        $model->sort = $max->sort + 1; // Set sort in Adding Form as ma x+ 1

        $this->render('create', array('model' => $model));
    }

    /**
     * Редактирование пункта меню.
     * 
     * @param integer $id Идинтификатор пункта меню для редактирования
     *
     * @return void
     */
    public function actionUpdate($id)
    {
        $model = $this->loadModel($id);

        // Uncomment the following line if AJAX validation is needed
        // $this->performAjaxValidation($model);
        if (($data = Yii::app()->getRequest()->getPost('MenuItem')) !== null) {

            $model->setAttributes($data);

            if ($model->save()) {

                Yii::app()->user->setFlash(
                    yupe\widgets\YFlashMessages::SUCCESS_MESSAGE,
                    Yii::t('MenuModule.menu', 'Record was created!')
                );

                $this->redirect(
                    (array) Yii::app()->getRequest()->getPost(
                        'submit-type', array('update', 'id' => $model->id)
                    )
                );
            }
        }

        $this->render('update', array('model' => $model));
    }

    /**
     * Удаляет модель пункта меню из базы.
     * Если удаление прошло успешно - возвращется в index
     * 
     * @param integer $id идентификатор пункта меню, который нужно удалить
     *
     * @return void
     *
     * @throws CHttpException If not POST-query
     */
    public function actionDelete($id)
    {
        if (Yii::app()->getRequest()->getIsPostRequest()) {
            // we only allow deletion via POST request
            $this->loadModel($id)->delete();

            Yii::app()->user->setFlash(
                yupe\widgets\YFlashMessages::SUCCESS_MESSAGE,
                Yii::t('MenuModule.menu', 'Record was removed!')
            );

            // если это AJAX запрос ( кликнули удаление в админском grid view), мы не должны никуда редиректить
            Yii::app()->getRequest()->getParam('ajax') !== null || $this->redirect(
                (array) Yii::app()->getRequest()->getPost('returnUrl', 'index')
            );
        } else {
            throw new CHttpException(
                400,
                Yii::t('MenuModule.menu', 'Bad request. Please don\'t try similar requests anymore!')
            );
        }
    }

    /**
     * Управление пунктами меню.
     *
     * @return void
     */
    public function actionIndex()
    {
        $model = new MenuItem('search');
        
        $model->unsetAttributes();  // clear any default values
        
        if (($data = Yii::app()->getRequest()->getParam('MenuItem')) !== null) {
            $model->setAttributes($data);
        }
        
        $this->render('index', array('model' => $model));
    }

    /**
     * Обновление дерева пунктов меню в завимости от родителя.
     *
     * @return void
     */
    public function actionDynamicParent()
    {
        if (Yii::app()->getRequest()->getIsAjaxRequest() && ($data = Yii::app()->getRequest()->getParam('MenuItem')) !== null) {
            $model = new MenuItem('search');
            
            $model->setAttributes($data);
            
            if ($model->menu_id) {
                if (isset($_GET['id'])) {
                    $model->id = $_GET['id'];
                }

                $data = $model->parentTree;
                
                foreach ($data as $value => $name) {
                    echo CHtml::tag('option', array('value' => $value), $name, true);
                }
            }
        }

        Yii::app()->end();
    }

    /**
     * Возвращает модель по указанному идентификатору
     * Если модель не будет найдена - возникнет HTTP-исключение.
     * 
     * @param integer идентификатор нужной модели
     *
     * @return void
     *
     * @throws CHttpException If MenuItem record not found
     */
    public function loadModel($id)
    {
        if (($model = MenuItem::model()->findByPk($id)) === null) {
            throw new CHttpException(
                404,
                Yii::t('MenuModule.menu', 'Page was not found!')
            );
        }

        return $model;
    }

    /**
     * Производит AJAX-валидацию
     * 
     * @param MenuItem модель, которую необходимо валидировать
     *
     * @return void
     */
    protected function performAjaxValidation(MenuItem $model)
    {
        if (Yii::app()->getRequest()->getIsAjaxRequest() && Yii::app()->getRequest()->getPost('ajax') === 'menuitem-form') {
            echo CActiveForm::validate($model);
            Yii::app()->end();
        }
    }
}

protected/modules/menu/views/menuitemBackend/_form.php
<?php
$form = $this->beginWidget('bootstrap.widgets.TbActiveForm', array(
    'id'                     => 'menu-item-form',
    'enableAjaxValidation'   => false,
    'enableClientValidation' => true,
    'type'                   => 'vertical',
    'htmlOptions'            => array('class' => 'well'),
    'inlineErrors'           => true,
)); ?>
    <div class="alert alert-info">
        <?php echo Yii::t('MenuModule.menu', 'Fields with'); ?>
        <span class="required">*</span>
        <?php echo Yii::t('MenuModule.menu', 'are required.'); ?>
    </div>

    <?php echo $form->errorSummary($model); ?>

<div class="wide row-fluid control-group <?php echo ($model->hasErrors('menu_id') || $model->hasErrors('parent_id')) ? 'error' : ''; ?>">
    <?php
    $menu_id   = '#' . CHtml::activeId($model, 'menu_id');
    $parent_id = '#' . CHtml::activeId($model, 'parent_id');
    ?>
    <div class="span3">
        <?php echo $form->dropDownListRow($model, 'menu_id', CHtml::listData(Menu::model()->findAll(), 'id', 'name'), array(
            'empty'               => Yii::t('MenuModule.menu', '--choose menu--'),
            'class'               => 'popover-help',
            'data-original-title' => $model->getAttributeLabel('menu_id'),
            'data-content'        => $model->getAttributeDescription('menu_id'),
            'ajax' => array(
                'type'       => 'POST',
                'url'        => $this->createUrl('/menu/menuitemBackend/dynamicparent', (!$model->isNewRecord ? array('id' => $model->id) : array())),
                'update'     => $parent_id,
                'beforeSend' => "function() {
                            $('" . $parent_id . "').attr('disabled', true);
                            if ($('" . $menu_id . " option:selected').val() == '')
                                return false;
                        }",
                'complete'   => "function() {
                            $('" . $parent_id . "').attr('disabled', false);
                        }",
            ),
        )); ?>
    </div>
    <div class="span4">
        <?php echo $form->dropDownListRow($model, 'parent_id', $model->parentTree, array('disabled' => ($model->menu_id) ? false : true) + array('encode' => false, 'class' => 'popover-help', 'data-original-title' => $model->getAttributeLabel('parent_id'), 'data-content' => $model->getAttributeDescription('parent_id'))); ?>
    </div>
</div>

    <div class="row-fluid control-group <?php echo $model->hasErrors("title") ? "error" : ""; ?>">
        <?php echo $form->textFieldRow($model, 'title', array('class' => 'popover-help span7', 'maxlength' => 255, 'data-original-title' => $model->getAttributeLabel('title'), 'data-content' => $model->getAttributeDescription('title'))); ?>
    </div>

    <div class="row-fluid control-group <?php echo $model->hasErrors("href") ? "error" : ""; ?>">
        <?php echo $form->textFieldRow($model, 'href', array('class' => 'popover-help span7', 'maxlength' => 255, 'data-original-title' => $model->getAttributeLabel('href'), 'data-content' => $model->getAttributeDescription('href'))); ?>
    </div>

    <div class="row-fluid control-group <?php echo $model->hasErrors("sort") ? "error" : ""; ?>">
        <?php echo $form->textFieldRow($model, 'sort', array('class' => 'popover-help span7', 'maxlength' => 255, 'data-original-title' => $model->getAttributeLabel('sort'), 'data-content' => $model->getAttributeDescription('sort'))); ?>
    </div>

    <div class="row-fluid control-group <?php echo $model->hasErrors('status') ? 'error' : ''; ?>">
        <?php echo $form->dropDownListRow($model, 'status', $model->statusList, array('class' => 'span7 popover-help', 'data-original-title' => $model->getAttributeLabel('status'), 'data-content' => $model->getAttributeDescription('status'))); ?>
    </div>

     <div class="row-fluid control-group <?php echo $model->hasErrors("regular_link") ? "error" : ""; ?>">
         <?php echo $form->checkBoxRow($model, 'regular_link', array('class' => 'popover-help', 'data-original-title' => $model->getAttributeLabel('regular_link'), 'data-content' => $model->getAttributeDescription('regular_link'))); ?>
    </div>

    <?php $collapse = $this->beginWidget('bootstrap.widgets.TbCollapse');?>
    <div class="accordion-group">
        <div class="accordion-heading">
            <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseOne">
                <?php echo Yii::t('MenuModule.menu','Extended settings');?>
            </a>
        </div>
        <div id="collapseOne" class="accordion-body collapse">
            <div class="accordion-inner">
                <div class="row-fluid control-group <?php echo $model->hasErrors("title_attr") ? "error" : ""; ?>">
                    <?php echo $form->textFieldRow($model, 'title_attr', array('class' => 'popover-help span7', 'maxlength' => 255, 'data-original-title' => $model->getAttributeLabel('title_attr'), 'data-content' => $model->getAttributeDescription('title_attr'))); ?>
                </div>
                <div class="row-fluid control-group <?php echo $model->hasErrors("class") ? "error" : ""; ?>">
                    <?php echo $form->textFieldRow($model, 'class', array('class' => 'popover-help span7', 'maxlength' => 50, 'data-original-title' => $model->getAttributeLabel('class'), 'data-content' => $model->getAttributeDescription('class'))); ?>
                </div>
                <div class="wide row-fluid control-group <?php echo ($model->hasErrors('before_link') || $model->hasErrors('after_link')) ? 'error' : ''; ?>">
                    <div class="span3">
                        <?php echo $form->textFieldRow($model, 'before_link', array('class' => 'popover-help span7', 'maxlength' => 255, 'data-original-title' => $model->getAttributeLabel('before_link'), 'data-content' => $model->getAttributeDescription('before_link'))); ?>
                    </div>
                    <div class="span4">
                        <?php echo $form->textFieldRow($model, 'after_link', array('class' => 'popover-help span7', 'maxlength' => 255, 'data-original-title' => $model->getAttributeLabel('after_link'), 'data-content' => $model->getAttributeDescription('after_link'))); ?>
                    </div>
                </div>
                <div class="wide row-fluid control-group <?php echo ($model->hasErrors('target') || $model->hasErrors('rel')) ? 'error' : ''; ?>">
                    <div class="span3">
                        <?php echo $form->textFieldRow($model, 'target', array('class' => 'popover-help span7', 'maxlength' => 10, 'data-original-title' => $model->getAttributeLabel('target'), 'data-content' => $model->getAttributeDescription('target'))); ?>
                    </div>
                    <div class="span4">
                        <?php echo $form->textFieldRow($model, 'rel', array('class' => 'popover-help span7', 'maxlength' => 10, 'data-original-title' => $model->getAttributeLabel('rel'), 'data-content' => $model->getAttributeDescription('rel'))); ?>
                    </div>
                </div>
                <div class="wide row-fluid control-group <?php echo ($model->hasErrors('condition_name') || $model->hasErrors('condition_denial')) ? 'error' : ''; ?>">
                    <div class="span4">
                        <?php echo $form->dropDownListRow($model, 'condition_name', $model->conditionList, array('empty' => '', 'class' => 'popover-help', 'data-original-title' => $model->getAttributeLabel('condition_name'), 'data-content' => $model->getAttributeDescription('condition_name'))); ?>
                    </div>
                    <div class="span3">
                        <?php echo $form->dropDownListRow($model, 'condition_denial', $model->conditionDenialList, array('class' => 'popover-help', 'data-original-title' => $model->getAttributeLabel('condition_denial'), 'data-content' => $model->getAttributeDescription('condition_denial'))); ?>
                    </div>
                </div>

            </div>
        </div>
    </div>
    <?php $this->endWidget();?>

    <br/>

    <?php $this->widget('bootstrap.widgets.TbButton', array(
        'buttonType' => 'submit',
        'type'       => 'primary',
        'label'      => $model->isNewRecord ? Yii::t('MenuModule.menu', 'Create menu item and continue') : Yii::t('MenuModule.menu', 'Save menu item and continue'),
    )); ?>
    <?php $this->widget('bootstrap.widgets.TbButton', array(
        'buttonType'  => 'submit',
        'htmlOptions' => array('name' => 'submit-type', 'value' => 'index'),
        'label'       => $model->isNewRecord ? Yii::t('MenuModule.menu', 'Create menu item and close') : Yii::t('MenuModule.menu', 'Save menu item and close'),
    )); ?>

<?php $this->endWidget(); ?>

protected/modules/menu/views/menuitemBackend/_search.php
<?php
$form = $this->beginWidget('bootstrap.widgets.TbActiveForm', array(
    'action'      => Yii::app()->createUrl($this->route),
    'method'      => 'get',
    'type'        => 'vertical',
    'htmlOptions' => array('class' => 'well'),
)); ?>

    <fieldset>
        <?php echo $form->textFieldRow($model, 'id') ?>
        <?php echo $form->textFieldRow($model, 'title'); ?>
        <?php echo $form->textFieldRow($model, 'href'); ?>
        <?php echo $form->dropDownListRow($model, 'menu_id', CHtml::listData(Menu::model()->findAll(), 'id', 'name'), array('empty' => Yii::t('MenuModule.menu', 'choose menu'))); ?>
        <?php echo $form->dropDownListRow($model, 'parent_id', $model->parentList); ?>
        <?php echo $form->dropDownListRow($model, 'condition_name', $model->conditionList); ?>
        <?php echo $form->dropDownListRow($model, 'condition_denial', $model->conditionDenialList); ?>
        <?php echo $form->textFieldRow($model, 'sort'); ?>
        <?php echo $form->dropDownListRow($model, 'status', $model->statusList); ?>
    </fieldset>

    <?php $this->widget('bootstrap.widgets.TbButton', array(
        'type'        => 'primary',
        'encodeLabel' => false,
        'buttonType'  => 'submit',
        'label'       => '<i class="icon-search icon-white">&nbsp;</i> ' . Yii::t('MenuModule.menu', 'Find menu item'),
    )); ?>

<?php $this->endWidget(); ?>

protected/modules/menu/views/menuitemBackend/create.php
<?php
    $this->breadcrumbs = array(        
        Yii::t('MenuModule.menu', 'Menu') => array('/menu/menuBackend/index'),
        Yii::t('MenuModule.menu', 'Menu items') => array('/menu/menuitemBackend/index'),
        Yii::t('MenuModule.menu', 'Create'),
    );

    $this->pageTitle = Yii::t('MenuModule.menu', 'Menu items - create');

    $this->menu = array(
        array('label' => Yii::t('MenuModule.menu', 'Menu'), 'items' => array(
            array('icon' => 'plus-sign', 'label' => Yii::t('MenuModule.menu', 'Create menu'), 'url' => array('/menu/menuBackend/create')),
            array('icon' => 'list-alt', 'label' => Yii::t('MenuModule.menu', 'Manage menu'), 'url' => array('/menu/menuBackend/index')),
        )),
        array('label' => Yii::t('MenuModule.menu', 'Menu items'), 'items' => array(
            array('icon' => 'plus-sign', 'label' => Yii::t('MenuModule.menu', 'Create menu item'), 'url' => array('/menu/menuitemBackend/create')),
            array('icon' => 'list-alt', 'label' => Yii::t('MenuModule.menu', 'Manage menu items'), 'url' => array('/menu/menuitemBackend/index')),
        )),
    );
?>
<div class="page-header">
    <h1>
        <?php echo Yii::t('MenuModule.menu', 'Menu item'); ?>
        <small><?php echo Yii::t('MenuModule.menu', 'create'); ?></small>
    </h1>
</div>

<?php echo $this->renderPartial('_form', array('model' => $model)); ?>